### ISSUE TITLE
index.php로 접속했을 때 secure key를 물어보는 화면이 뜨지 않음

### ISSUE THREAD

**Issue by gaejabong** [xpressengine/xpressengine-migration#4]
https://domain/migration/index.php

- 이런식으로 접근하면 아래와 같은 화면이 나오고 securekey를 물어보지 않습니다.
- securekey 파라미터로 잘못된 값을 넣었을 때도 아래와 같은 화면이 나옵니다.

![image](https://user-images.githubusercontent.com/978944/46738245-a8b16380-ccd8-11e8-8de4-e637da1756de.png)

파라미터로 정상적인 UUID 값을 넘길 때는 마이그레이션 툴이 작동합니다.

**Comment by ghost** [comment]
네. 아직 정리되지 않은 부분이 너무 많아 사용에 불편이 큽니다.
