### ISSUE TITLE
file_put_contents(access.log): failed to open stream: Permission denied 오류

### ISSUE THREAD

**Issue by gaejabong** [xpressengine/xpressengine-migration#5]
서버 환경에서 웹서버 데몬과 계정의 사용자 권한이 달라서 발생하는 문제인 것 같습니다.
디렉토리 권한을 ```webuser:사용자그룹``` 으로 주었을 때는 발생하지 않네요.

**Comment by ghost** [comment]
아. 해당 파일 제거했어야 했는데 남아 있었네요.
